# Generated by Django 3.0.3 on 2020-03-06 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fac_Id', models.CharField(max_length=5)),
                ('FacName', models.CharField(max_length=40)),
                ('Value', models.IntegerField()),
            ],
        ),
    ]
