# Generated by Django 3.0.3 on 2020-04-25 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentalCourses',
            fields=[
                ('CourseId', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('CourseName', models.CharField(max_length=50)),
                ('Semester', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MembersChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacName', models.CharField(max_length=50)),
                ('priority1', models.CharField(max_length=40)),
                ('priority2', models.CharField(max_length=40)),
                ('priority3', models.CharField(max_length=40)),
                ('priority4', models.CharField(max_length=40)),
                ('priority5', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='SemesterCheck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='deptmembers',
            name='Value',
        ),
    ]
