# Generated by Django 3.0.3 on 2020-03-06 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0003_remove_facultylist_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultylist',
            old_name='Fac_Id',
            new_name='FacId',
        ),
    ]
