# Generated by Django 3.0.3 on 2020-03-06 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0004_auto_20200306_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.CharField(max_length=5)),
                ('CourseName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='DepartmentalCourses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.CharField(max_length=5)),
                ('CourseName', models.CharField(max_length=40)),
            ],
        ),
    ]
