# Generated by Django 3.0.3 on 2020-03-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0005_courselist_departmentalcourses'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CourseId', models.CharField(max_length=5)),
                ('CourseName', models.CharField(max_length=40)),
            ],
        ),
    ]
