# Generated by Django 3.0.3 on 2020-03-14 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0006_templist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deptmembers',
            name='Value',
        ),
    ]
