# Generated by Django 3.0.3 on 2020-03-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0007_remove_deptmembers_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CourseList',
        ),
        migrations.DeleteModel(
            name='DepartmentalCourses',
        ),
    ]
