# Generated by Django 3.0.3 on 2020-03-14 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0010_courselist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courselist',
            old_name='CoueseName',
            new_name='CourseName',
        ),
    ]
