# Generated by Django 3.0.3 on 2020-03-14 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0011_auto_20200314_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='departmentalcourses',
            old_name='CoueseName',
            new_name='CourseName',
        ),
    ]
