# Generated by Django 3.0.3 on 2020-03-14 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0012_auto_20200314_1032'),
    ]

    operations = [
        migrations.CreateModel(
            name='MembersChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacId', models.CharField(max_length=5)),
                ('priority1', models.CharField(max_length=40)),
                ('priority2', models.CharField(max_length=40)),
                ('priority3', models.CharField(max_length=40)),
                ('priority4', models.CharField(max_length=40)),
                ('priority5', models.CharField(max_length=40)),
            ],
        ),
        migrations.DeleteModel(
            name='CourseList',
        ),
        migrations.DeleteModel(
            name='FacultyList',
        ),
        migrations.DeleteModel(
            name='TempList',
        ),
    ]
