# Generated by Django 3.0.3 on 2020-03-17 03:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0013_auto_20200314_1733'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeptMembers',
        ),
        migrations.DeleteModel(
            name='MembersChoice',
        ),
    ]
