# Generated by Django 3.0.3 on 2020-03-17 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0014_auto_20200317_0912'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeptMembers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FacId', models.CharField(max_length=5)),
                ('FacName', models.CharField(max_length=40)),
                ('priority1', models.CharField(max_length=40)),
                ('priority2', models.CharField(max_length=40)),
                ('priority3', models.CharField(max_length=40)),
                ('priority4', models.CharField(max_length=40)),
                ('priority5', models.CharField(max_length=40)),
            ],
        ),
    ]
