# Generated by Django 3.0.3 on 2020-04-12 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0017_memberschoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberschoice',
            old_name='FacId',
            new_name='FacName',
        ),
    ]
