# Generated by Django 3.0.3 on 2020-04-12 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0018_auto_20200412_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberschoice',
            name='FacName',
            field=models.CharField(max_length=50),
        ),
    ]
