# Generated by Django 3.0.3 on 2020-04-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyregistration', '0020_semestercheck'),
        ('facultyregistration', '0002_auto_20200425_1041'),
    ]

    operations = [
    ]
